# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(328, 233)
        self.unpackButton = QtWidgets.QPushButton(Dialog)
        self.unpackButton.setGeometry(QtCore.QRect(20, 50, 291, 51))
        self.unpackButton.setObjectName("unpackButton")
        self.repackButton = QtWidgets.QPushButton(Dialog)
        self.repackButton.setGeometry(QtCore.QRect(20, 110, 291, 51))
        self.repackButton.setObjectName("repackButton")
        self.fallbackButton = QtWidgets.QPushButton(Dialog)
        self.fallbackButton.setGeometry(QtCore.QRect(20, 170, 291, 51))
        self.fallbackButton.setObjectName("fallbackButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Snap Lens Tool"))
        self.unpackButton.setToolTip(_translate("Dialog", "<html><head/><body><p>Select snap lens file for unpacking</p></body></html>"))
        self.unpackButton.setText(_translate("Dialog", "Unpack Lens"))
        self.repackButton.setToolTip(_translate("Dialog", "<html><head/><body><p>Select unpacked snap lens files for re-packing</p></body></html>"))
        self.repackButton.setText(_translate("Dialog", "Re-Pack Lens"))
        self.fallbackButton.setToolTip(_translate("Dialog", "<html><head/><body><p>Fallback mode can fix issues with Snap Camera</p></body></html>"))
        self.fallbackButton.setText(_translate("Dialog", "Set Fallback Mode"))
        self.label.setText(_translate("Dialog", "Early Alpha Version"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
